export enum TipoAutomovil {
  SEDAN = 'SEDAN',
  SUV = 'SUV',
  HATCHBACK = 'HATCHBACK',
  COUPE = 'COUPE',
  CONVERTIBLE = 'CONVERTIBLE',
  CAMIONETA = 'CAMIONETA',
  MINIVAN = 'MINIVAN',
  VAGONETA = 'VAGONETA',
  DEPORTIVO = 'DEPORTIVO',
}
